### ISSUE TITLE
is custom font supported?

### ISSUE THREAD

**Issue by mat-lo** [go-p5/p5#56]
I looked for it in the documentation but it's not there so I guess not

**Comment by sbinet** [comment]
thanks for the report.

there's indeed no exposed API to do that at the moment.
as the underlying [Gio](https://gioui.org) library allows for such a thing, it wouldn't be too difficult to achieve such a thing.

do you expect to be able to have different fonts flavors (italic/bold/mono), different fonts altogether (helvetica/noto,....) or both, on a per-text basis? or something at the "application" level would suffice?

**Comment by mat-lo** [comment]
Thanks @sbinet for your quick reply! 
It would be great if we could use a custom font file altogether, just like `loadFont()` in p5.js.
